id: IBB2E288B
ocr_import_info:
  timestamp: '2023-09-25T16:18:49.706188+00:00'
  batch_id: batch-4cd4
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-25 16:34:13.247963+00:00
last_modified: 2023-09-25 16:34:13.247970+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM5187
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM5187
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་བསྡུས་དོན་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9599411027883018
  ocr_word_median_confidence_index: 0.99703705
bases:
  I1NLM5187_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM5187_001
      total_pages: 382
      volume_number: 1
    order: 1
    base_file: I1NLM5187_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99703705
      ocr_word_mean_confidence_index: 0.9599411027883018
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
